// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vegaApp.models;

namespace vegaApp.Migrations
{
    [DbContext(typeof(VegaContext))]
    [Migration("20190616155406_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("vegaApp.models.Feature", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Feature1"
                        },
                        new
                        {
                            id = 2,
                            name = "Feature2"
                        },
                        new
                        {
                            id = 3,
                            name = "Feature3"
                        });
                });

            modelBuilder.Entity("vegaApp.models.Make", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("id");

                    b.ToTable("Makes");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Make1"
                        },
                        new
                        {
                            id = 2,
                            name = "Make2"
                        },
                        new
                        {
                            id = 3,
                            name = "Make3"
                        });
                });

            modelBuilder.Entity("vegaApp.models.Model", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("makeId");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("id");

                    b.HasIndex("makeId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            id = 1,
                            makeId = 3,
                            name = "Model1"
                        },
                        new
                        {
                            id = 2,
                            makeId = 2,
                            name = "Model2"
                        },
                        new
                        {
                            id = 3,
                            makeId = 1,
                            name = "Model3"
                        });
                });

            modelBuilder.Entity("vegaApp.models.Model", b =>
                {
                    b.HasOne("vegaApp.models.Make", "make")
                        .WithMany("models")
                        .HasForeignKey("makeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
